# Simple makefile for creating homework 01
CC=gcc
CFLAGS=-g -Wall

all: 491hw1 491hw1_t 491hw1_1st 491hw1_2nd

491hw1:
	$(CC) $(CFLAGS) -o hw01ryfcs491 491hw1.c

491hw1_t:
	$(CC) $(CFLAGS) -o hw01ryfcs491_t 491hw1_t.c

491hw1_1st:
	$(CC) $(CFLAGS) -o hw01ryfcs491_1st 491hw1_1st.c

491hw1_2nd:
	$(CC) $(CFLAGS) -o hw01ryfcs491_2nd 491hw1_2nd.c

clean:
	$(RM) hw01ryfcs491 hw01ryfcs491_t